apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-manager
  namespace: sandbox-system
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
