apiVersion: batch/v1
kind: CronJob
metadata:
  name: sandbox-gc
  namespace: sandbox-system
spec:
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: harbor-registry-secret
