apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- access/ingress.yaml
images:
- name: sandbox-manager
  newName: harbor.pullot.com:28443/agentsmith/sandbox-manager
  newTag: 2.0.2
- name: sandbox-runner
  newName: harbor.pullot.com:28443/agentsmith/sandbox-runner
  newTag: 1.0.0
- name: sandbox-gc
  newName: harbor.pullot.com:28443/agentsmith/sandbox-gc
  newTag: 1.0.0
patches:
- path: patches/manager-replicas.yaml
- path: patches/resource-limits.yaml
- path: patches/security-hardening.yaml
- path: patches/configmap-ttl.yaml
- path: patches/configmap-runner-image-full.yaml
- path: patches/configmap-runner-image.yaml
- path: patches/configmap-gc.yaml
- path: patches/image-pull-secrets.yaml
- path: patches/gc-image-pull-secrets.yaml
