apiVersion: v1
kind: Service
metadata:
  name: agentsmith-sandbox-control-plane
  namespace: sandbox-system
  labels:
    app.kubernetes.io/component: asbcp
spec:
  selector:
    app: agentsmith-sandbox-control-plane
    app.kubernetes.io/component: asbcp
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
