apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-manager
  namespace: sandbox-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-manager-role
  namespace: sandbox
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch","create","delete","patch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-manager-rb
  namespace: sandbox
subjects:
- kind: ServiceAccount
  name: sandbox-manager
  namespace: sandbox-system
roleRef:
  kind: Role
  name: sandbox-manager-role
  apiGroup: rbac.authorization.k8s.io
