apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-gc
  namespace: sandbox-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-gc-role
  namespace: sandbox
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-gc-rb
  namespace: sandbox
subjects:
- kind: ServiceAccount
  name: sandbox-gc
  namespace: sandbox-system
roleRef:
  kind: Role
  name: sandbox-gc-role
  apiGroup: rbac.authorization.k8s.io
