apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sandbox-manager
  newName: sandbox-manager
  newTag: 2.0.2
- name: sandbox-runner
  newName: sandbox-runner
  newTag: 1.0.0
patches:
- path: patches/manager-replicas.yaml
- path: patches/resource-limits.yaml
- path: patches/configmap-ttl.yaml
- path: patches/configmap-runner-image-full.yaml
- path: patches/configmap-runner-image.yaml
