apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: sandbox-manager
  newName: localhost:5001/sandbox-manager
  newTag: 2.0.3
- name: sandbox-runner
  newName: localhost:5001/sandbox-runner
  newTag: 1.0.0
patches:
- path: patches/afscp-config.yaml
- path: patches/manager-replicas.yaml
- path: patches/resource-limits.yaml
- path: patches/image-pull-secrets.yaml
