apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: agentsmith-sandbox-control-plane
  newName: localhost:5001/agentsmith-sandbox-control-plane
  newTag: 2.0.15
patches:
- path: patches/afscp-config.yaml
- path: patches/asbcp-replicas.yaml
- path: patches/resource-limits.yaml
- path: patches/image-pull-secrets.yaml
